<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AddDeviceForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AddLoanForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AddMember.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="LoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="RegisterForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UpdateDeviceForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>